In [22]:
import numpy as np

# Операції random та arange
array = np.arange(start=10, stop=25, step=1)
rand_ar = np.random.randint(1, size=5)
print(array)
print(rand_ar)

# CRUD

# create
scalar = np.array(15)
vector = np.arange(start=5, stop=20, step=2)
matrix = np.random.randint(low=1, high=20, size=(5, 5))

# read
print("\n Scalar: ", scalar)
print("Vector: ", vector)
print("Matrix: \n", matrix)

# update
scalar = vector[2]
vector[5] = matrix[1,3]
matrix[3,4] = 54
print("\n Scalar update: ", scalar)
print("Vector update: ", vector)
print("Matrix update: \n", matrix)

# delete
vector = np.delete(vector, [2])
matrix = np.delete(matrix, 1, 0)
print("\n Vector delete: ", vector)
print("Matrix delete: \n", matrix)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 0 0 0 0]

 Scalar:  15
Vector:  [ 5  7  9 11 13 15 17 19]
Matrix: 
 [[13  6  4  1 14]
 [16 15  6  9 12]
 [15 14 13  7 18]
 [ 7 11  5  9 13]
 [10 12 16 15 17]]

 Scalar update:  9
Vector update:  [ 5  7  9 11 13  9 17 19]
Matrix update: 
 [[13  6  4  1 14]
 [16 15  6  9 12]
 [15 14 13  7 18]
 [ 7 11  5  9 54]
 [10 12 16 15 17]]

 Vector delete:  [ 5  7 11 13  9 17 19]
Matrix delete: 
 [[13  6  4  1 14]
 [15 14 13  7 18]
 [ 7 11  5  9 54]
 [10 12 16 15 17]]


In [32]:
import pandas as pd
import numpy as np

# Створення DF зі списку
data =  [['Mike', 'Lake'],
        ['Wolter', "White"],
        ['Lila', 'Pinkman']]
df = pd.DataFrame(data, columns=['Name','Lastname'])
print(df)
print('--------------------------------------------')

# Створення DF зі словника
data2 = {'Name': ['Mike', 'Wolter', 'Lila'],
        'Age': [20, 51, 25],
        'City': ['Los Angeles', 'New York', 'Chicago']}

df2 = pd.DataFrame(data2)
print(df2)
print('--------------------------------------------')
        
# Створення DF зі списку словників
data3 = [{'Name': 'Mike','Age': 20, 'City':'Los Angeles' },
         {'Name': 'Wolter','Age': 51, 'City':'New York' },
         {'Name': 'Lila','Age': 25, 'City':'Chicago' }]

df3 = pd.DataFrame(data3)
print(df3)
print('--------------------------------------------')

print(df.head(2))
print('--------------------------------------------')
print(df.tail(1))
print('--------------------------------------------')
print(df.loc[['Lastname'])
print('--------------------------------------------')
print(df2.iloc[[1,2]])
print('--------------------------------------------')
print(df2.describe())

     Name Lastname
0    Mike     Lake
1  Wolter    White
2    Lila  Pinkman
--------------------------------------------
     Name  Age         City
0    Mike   20  Los Angeles
1  Wolter   51     New York
2    Lila   25      Chicago
--------------------------------------------
     Name  Age         City
0    Mike   20  Los Angeles
1  Wolter   51     New York
2    Lila   25      Chicago
--------------------------------------------
     Name Lastname
0    Mike     Lake
1  Wolter    White
--------------------------------------------
   Name Lastname
2  Lila  Pinkman
--------------------------------------------


KeyError: 'Lastname'